### ISSUE TITLE
Some types are broken again

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#54]
e.g.
![image](https://user-images.githubusercontent.com/2642209/83438275-2296e300-a40f-11ea-9289-731015bfce4c.png)

cc: @alexperovich

**Comment by alexperovich** [comment]
This is a very strange error, the file exists where it is supposed to be... I'll investigate.

The index also hasn't been building successfully since the 25th because dotnet/aspnetcore has a file path that is too long....

**Comment by tannergooding** [comment]
Would it be possible to index based on pre-built sources rather than dynamically building the sources (which seems to be incredibly error prone based on various infrastructure changes, etc)?

We already run CI and create binaries on an almost per merge basis and the PDBs should be fully source-linked back to GitHub and of course contain all the relevant type information when combined with the actual assembly.

**Comment by alexperovich** [comment]
this request failure appears to be something that changed in the IIS configuration on app services... the RequestFilteringModule is 404ing the request before the app even gets it.

**Comment by alexperovich** [comment]
The indexer requires the full binlog and all the sources in the same locations they were when the binlog was created, I don't know of any good way to get that without just building the repo.

**Comment by alexperovich** [comment]
.... its because the full path to the file was used... rather than the relative path. And the full path contains "bin" so IIS is masking that path out because ancient asp.net apps deployed binaries into their webroot..... I'll try to fix it with some web.config shenanigans.

**Comment by alexperovich** [comment]
Yep, that fixed it. The long path problem is still happening though.

**Comment by alexperovich** [comment]
weird, core.longpaths was just not set for the repos. I fixed that and a build is running.

**Comment by stephentoub** [comment]
Thanks for investigating, @alexperovich.
