### ISSUE TITLE
Some types show the platform not supported implementation 

### ISSUE THREAD

**Issue by stephentoub** [dotnet/source-indexer#93]
e.g.
https://source.dot.net/#System.IO.Pipes/System.IO.Pipes.notsupported.cs,302d4e678aae2a88

**Comment by alexperovich** [comment]
This means that the build got changed in such a way that this command (https://github.com/dotnet/runtime/blob/main/eng/pipelines/runtime-official.yml#L58) now doesn't build this library with the right parameters. I don't know enough about the platform not supported stuff to know exactly why though

**Comment by alexperovich** [comment]
I tried to repro it, but the build doesn't even accept that list of subsets when I run locally. Somehow it still runs in the CI build though https://dev.azure.com/dnceng/internal/_build/results?buildId=1923146&view=logs&j=316d5c15-0c50-544e-8051-e6b14a1ab674&t=4e01507e-10cc-507d-f6d0-adc59e92bcb8

**Comment by alexperovich** [comment]
Ahh no, I had some outdated sources, I have it running now.

**Comment by alexperovich** [comment]
Okay, I figured it out. The build of System.IO.Pipes.csproj for some reason decides to run compile twice. The first one is compiling not-supported sources into `D:\dotnet\runtime\artifacts\obj\System.IO.Pipes\Debug\net7.0\System.IO.Pipes.dll` and the second csc invocation is the normal sources into `D:\dotnet\runtime\artifacts\obj\System.IO.Pipes\Debug\net7.0-unix\System.IO.Pipes.dll`. Due to the way the indexer reads things, it sees the first csc invocation and it doesn't match any of the exclusions for ref assemblies and similar, so it gets processed, then the second csc invocation gets ignored because that project has already been processed.

**Comment by alexperovich** [comment]
The first Csc invocation appears to be inside the ResolveProjectReferences target of System.IO.Pipes.AccessControl.csproj.

**Comment by alexperovich** [comment]
Yep, the build of System.IO.Pipes triggered by the ResolveProjectReferences step in System.IO.Pipes.AccessControl builds with TargetFramework=net7.0, which produces not-supported sources. The normal build of System.IO.Pipes has TargetFramework=net7.0-Unix

**Comment by stephentoub** [comment]
cc: @ViktorHofer

**Comment by alexperovich** [comment]
The `ChooseBestP2PTargetFrameworkTask` from microsoft.dotnet.build.tasks.targetframework is where that wrong tfm comes from.

**Comment by ViktorHofer** [comment]
Does someone know when this started happening? The last related infra change that I can think of happened months ago.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/runtime/pull/73588 fixes the underlying issue with System.IO.Pipes.AccessControl. I looked at the code base and couldn't find other cases where a PNSE configuration was unintentionally built.

**Comment by stephentoub** [comment]
Thank you both for fixing it.
